<?php
/**
 * Magento Module developed by NoStress Commerce
 *
 * NOTICE OF LICENSE
 *
 * This program is licensed under the Koongo software licence (by NoStress Commerce).
 * With the purchase, download of the software or the installation of the software
 * in your application you accept the licence agreement. The allowed usage is outlined in the
 * Koongo software licence which can be found under https://docs.koongo.com/display/koongo/License+Conditions
 *
 * Any modification or distribution is strictly forbidden. The license
 * grants you the installation in one application. For multiuse you will need
 * to purchase further licences at https://store.koongo.com/.
 *
 * See the Koongo software licence agreement for more details.
 * @copyright Copyright (c) 2017 NoStress Commerce (http://www.nostresscommerce.cz, http://www.koongo.com/)
 *
 */

// @codingStandardsIgnoreFile

?>
<script>
require([
    "jquery",
    "uiRegistry",
    "Magento_Ui/js/modal/alert",
    'Magento_Ui/js/modal/prompt',
    "collapsable",
    "prototype"
], function (jQuery, rg, alert, prompt) 
{
	jQuery( document ).ready(function() 
	{
		//render shipping intervals 0.5s after page load
		setTimeout( function(){ 
			jQuery('#manage-options-panel').trigger('render');
			updateShippingTable($('channel_profile_dependent_attribute'));			
		  }  , 500 );

		//render shipping intervals 3s after page load(to ensure that table is rendered)
		setTimeout( function(){ 
			jQuery('#manage-options-panel').trigger('render');
			updateShippingTable($('channel_profile_dependent_attribute'));			
		  }  , 3000 );	
		  
		//render shipping intervals 10s after page load(to ensure that table is rendered)  
		setTimeout( function(){ 
			jQuery('#manage-options-panel').trigger('render');
			updateShippingTable($('channel_profile_dependent_attribute'));			
		  }  , 10000 );		 					
	});  	  
});

</script>
